// Code generated by gen-models. DO NOT EDIT.
package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

type NamecheapCredential struct {
	ID               uuid.UUID  `gorm:"type:uuid;primaryKey"`
	AccountID        uuid.UUID  `gorm:"type:uuid;index:idx_namecheap_credentials_account_id;uniqueIndex:uq_namecheap_credentials_account_api_user_sandbox,priority:1"`
	ProfileID        *uuid.UUID `gorm:"type:uuid"`
	Label            string     `gorm:"type:varchar(255)"`
	APIUser          string     `gorm:"type:varchar(255);uniqueIndex:uq_namecheap_credentials_account_api_user_sandbox,priority:2"`
	UserName         string     `gorm:"type:varchar(255)"`
	APIKey           string     `gorm:"type:text"`
	ClientIP         string     `gorm:"type:varchar(45)"`
	Sandbox          bool       `gorm:"type:boolean;uniqueIndex:uq_namecheap_credentials_account_api_user_sandbox,priority:3"`
	LastVerifiedAt   *time.Time `gorm:"type:timestamp"`
	LastErrorMessage *string    `gorm:"type:text"`
	CreatedAt        time.Time  `gorm:"autoCreateTime"`
	UpdatedAt        time.Time  `gorm:"autoUpdateTime"`
}

func (NamecheapCredential) TableName() string { return "sites.namecheap_credentials" }

func (m *NamecheapCredential) BeforeCreate(tx *gorm.DB) (err error) {
	if m.ID == uuid.Nil {
		m.ID, err = uuid.NewV7()
	}
	return
}

var NamecheapCredentialCols = struct {
	ID, AccountID, ProfileID, Label, APIUser, UserName, APIKey,
	ClientIP, Sandbox, LastVerifiedAt, LastErrorMessage, CreatedAt, UpdatedAt string
}{
	ID:               "id",
	AccountID:        "account_id",
	ProfileID:        "profile_id",
	Label:            "label",
	APIUser:          "api_user",
	UserName:         "user_name",
	APIKey:           "api_key",
	ClientIP:         "client_ip",
	Sandbox:          "sandbox",
	LastVerifiedAt:   "last_verified_at",
	LastErrorMessage: "last_error_message",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

const (
	NamecheapCredentialPk                      = "namecheap_credentials_pkey"
	NamecheapCredentialUkAccountApiUserSandbox = "uq_namecheap_credentials_account_api_user_sandbox"
)
